spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/enriquecamejo/garbanzo.git/
          search-paths:
              - "demo-properties/{application}"
